#!/bin/bash

echo "# This file has been generated by the prepare-env script." > .env
echo "# You can overwrite the following values at your convenience." >> .env
echo "# Please refer to the .env.example file if needed." >> .env

echo "" >> .env

echo "NODE_ENV=DEV" >> .env

echo "" >> .env

echo "DATABASE_URL='postgresql://postgres:postgres@localhost:5410/db-kata'" >> .env
echo "DATABASE_URL_WITH_SCHEMA=${DATABASE_URL}?schema=public" >> .env