#!/bin/bash

echo "# This file has been generated by the prepare-env script." > .env
echo "# You can overwrite the following values at your convenience." >> .env

echo "" >> .env

echo "KATA_ENV=DEV" >> .env

echo "" >> .env

echo "# GLOBALE APP" >> .env

echo "PORT=4071" >> .env
echo "WEB_APP_URL=http://localhost:4079" >> .env
echo "NAME_APP=API_KATA" >> .env

echo "" >> .env

echo "# JWT" >> .env
echo "JWT_SECRET_AT=gH6mQt4XWP9vJH2kSmBZcOJY7oPnB3RmYuSpRt9lKnA=" >> .env
echo "JWT_SECRET_RT=xV8sCr2WTY6kNZ5jRlVcDOIU4qKtR7BnOvLyPp8kAmY=" >> .env

echo "" >> .env

echo "# MAILING" >> .env
echo "SENDGRID_API_KEY=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" >> .env
echo "AUTOMATIC_MAIL=jeje97180@hotmail.fr" >> .env

echo "" >> .env

echo "# EVENTS PLANNING" >> .env
echo "SUGGESTIONS_SLOTS_NUMBERS=4" >> .env
